import html5 from '../../Assets/html5.png'
import css from '../../Assets/css3.png'
import bootstrap from '../../Assets/Bootstrap_logo.svg.png'
import firebase from '../../Assets/firebase.png'
import github from '../../Assets/github.png'
import javascript from '../../Assets/javascript.png'
import reactjs from '../../Assets/React-icon.svg.png'
import tailwindcss from '../../Assets/Tailwind_CSS_Logo.svg.png'

export const skillsItems = [
    { id: 1, image: [html5], alt: 'HTML5 icon', title: 'HTML', text: 'Hypertext Markup Language revision 5 (HTML5) is markup language for the structure and presentation of World Wide Web contents. HTML5 supports the traditional HTML and XHTML-style syntax and other new features in its markup, New APIs, XHTML and error handling.' },
    { id: 2, image: [css], alt: 'CSS icon', title: 'CSS', text: 'Cascading Style Sheets Level 3 (CSS3) is the iteration of the CSS standard used in the styling and formatting of Web pages. CSS3 incorporates the CSS2 standard with some changes and improvements.\n\nA key change is the division of standard into separate modules, which makes it easier to learn and understand. As of February 2014, the standard is still under development by the World Wide Web Consortium (W3C), but a number of the CSS3 properties have been implemented in the latest versions of some Web browsers.'},
    { id: 3, image: [bootstrap], alt: 'Bootstrap icon', title: 'Bootstrap',text: 'Bootstrap is a free, open source front-end development framework for the creation of websites and web apps. Designed to enable responsive development of mobile-first websites, Bootstrap provides a collection of syntax for template designs.\n\nAs a framework, Bootstrap includes the basics for responsive web development, so developers only need to insert the code into a pre-defined grid system. The Bootstrap framework is built on Hypertext Markup Language (HTML), cascading style sheets (CSS) and JavaScript. Web developers using Bootstrap can build websites much faster without spending time worrying about basic commands and functions.' },
    { id: 4, image: [firebase], alt: 'Firebase icon', title: 'Firebase', text: 'Firebase is a set of hosting services for any type of application (Android, iOS, Javascript, Node.js, Java, Unity, PHP, C++ ...). It offers NoSQL and real-time hosting of databases, content, social authentication (Google, Facebook, Twitter and Github), and notifications, or services, such as a real-time communication server.' },
    { id: 5, image: [github], alt: 'GitHub icon', title: 'GitHub', text: 'GitHub is a code hosting platform for version control and collaboration. It lets you and others work together on projects from anywhere.'},
    { id: 6, image: [javascript], alt: 'JavaScript icon', title: 'JavaScript', text: 'Javascript (JS) is a scripting languages, primarily used on the Web. It is used to enhance HTML pages and is commonly found embedded in HTML code. JavaScript is an interpreted language. Thus, it does not need to be compiled. JavaScript renders web pages in an interactive and dynamic fashion. This allowing the pages to react to events, exhibit special effects, accept variable text, validate data, create cookies, detect a users browser, etc.' },
    { id: 7, image: [reactjs], alt: 'React icon', title: 'React', text: 'React.js, more commonly known as React, is a free, open-source JavaScript library. It works best to build user interfaces by combining sections of code (components) into full websites. Originally built by Facebook, Meta and the open-source community now maintain it. One of the good things about React is that you can use it as much or as little as you want! For example, you can build your entire site in React or just use one single React component on one page.\n\nReact.js is built using JSX – A combination of JavaScript and XML. Elements are created using JSX, then use JavaScript to render them on your site. While React has a steep learning curve for a junior developer, it’s quickly shaping into one of the most popular and in-demand JavaScript libraries.' },
    { id: 8, image: [tailwindcss], alt: 'Tailwind icon', title: 'Tailwind', text: 'Tailwind CSS is a "utility-first" CSS framework that provides a deep catalog of CSS classes and tools that lets you easily get started styling your website or application.\n\nTaildwinds solution is to provide a wide variety of CSS classes that each have their own focused use. Instead of a class called .btn that is created with a bunch of CSS attributes directly, in Tailwind, you would either apply a bunch of classes like bg-blue-500 py-2 px-4 rounded to the button element or build a .btn class by applying those utility class to that selector.' }
]